<?php

namespace AppBundle\Repository;

/**
 * DCFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DCFileRepository extends \Doctrine\ORM\EntityRepository
{
}
