<?php

namespace AppBundle\Repository;

/**
 * DockersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DockersRepository extends \Doctrine\ORM\EntityRepository
{
}
